
 ### 1.Load a CSV dataset into a Pandas DataFrame

In [45]:
import pandas as pd

In [46]:
df=pd.read_csv(r"Original_Combined_dataset.csv")

In [47]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [48]:
len(df)

1000

In [49]:
df=pd.DataFrame(df)

In [50]:
df

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

### 2.Explore data (head/tail, shape, columns, data types).

In [51]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [52]:
df.head(10)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,NaN,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",NaN,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
6,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
8,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Super King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
9,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets

In [53]:
df.tail()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [54]:
df.shape

(1000, 24)

In [55]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [56]:
df.dtypes

product_id                  int64
title                      object
product_description        object
rating                    float64
ratings_count               int64
initial_price               int64
discount                  float64
final_price                object
currency                   object
images                     object
delivery_options           object
product_details            object
breadcrumbs                object
product_specifications     object
amount_of_stars            object
what_customers_said        object
seller_name                object
sizes                      object
videos                     object
seller_information         object
variations                 object
best_offer                 object
more_offers                object
category                   object
dtype: object

In [57]:
df["discount"].dtypes

dtype('float64')

In [58]:
df.describe()

         product_id     rating  ratings_count  initial_price    discount
count  1.000000e+03  1000.0000    1000.000000     1000.00000  879.000000
mean   1.713437e+07     3.6215      76.691000     2723.24100   53.503982
std    3.813766e+06     1.3744     241.114263     2408.69736   18.029201
min    5.868460e+05     0.0000       0.000000      249.00000    1.000000
25%    1.511501e+07     3.7000       7.000000     1399.00000   44.000000
50%    1.820890e+07     4.1000      17.000000     1999.00000   56.000000
75%    1.902737e+07     4.3000      58.000000     3299.00000   66.000000
max    2.274707e+07     5.0000    4441.000000    22199.00000   88.000000

In [59]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

### 3.Handle missing values (identify, fill/drop).

In [61]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [62]:
print("Total missing values:",df.isnull().sum().sum())

Total missing values: 2639

In [63]:
#Drop the columns that are to empty to be useful
#what_customer_said=573,videos=781,variations=562
df=df.drop(columns=["what_customers_said","videos","variations"])
print("Remaining columns:",df.shape[1])

Remaining columns: 21

In [64]:
#Filling discount missing values with 0
df["discount"]=df["discount"].fillna(0)
print("Missing values in discount:",df["discount"].isnull().sum())

Missing values in discount: 0

In [65]:
#filling seller_name with unknown
df["seller_name"]=df["seller_name"].fillna('unknown')
print("Missing values in seller_name:",df["seller_name"].isnull().sum())

Missing values in seller_name: 0

In [66]:
#filling seller_information with Not available
df["seller_information"]=df["seller_information"].fillna("Not Available")
print("Missing values in seller_information:",df["seller_information"].isnull().sum())

Missing values in seller_information: 0

In [67]:
#checking missing values in dataframe
df.isnull().sum()

product_id                0
title                     0
product_description       0
rating                    0
ratings_count             0
initial_price             0
discount                  0
final_price               0
currency                  0
images                    0
delivery_options          0
product_details           0
breadcrumbs               0
product_specifications    0
amount_of_stars           0
seller_name               0
sizes                     0
seller_information        0
best_offer                0
more_offers               0
category                  0
dtype: int64

### 4.Perform basic operations (filter rows, select columns).

In [68]:
#select columns
df[["title","rating","final_price"]].head()

            title  rating  final_price
0     Lino Perros     3.8  "₹3,995.00"
1  Tommy Hilfiger     4.5  "₹2,899.00"
2           Lavie     4.4  "₹2,999.00"
3          F Gear     4.4  "₹1,675.00"
4       MYTRIDENT     4.7  "₹2,899.00"

In [69]:
df["seller_name"]

0             unknown
1             unknown
2             unknown
3             unknown
4             unknown
            ...
995           unknown
996           unknown
997           unknown
998    Tru███m R███il
999           unknown
Name: seller_name, Length: 1000, dtype: object

In [70]:
#Filter Rows

In [71]:
#filtering products with ratings above 5
high_rated=df[df["rating"]>4.5]
print("proucts with rating above 4.5:",len(high_rated))
high_rated[["title","category","rating"]].head()

proucts with rating above 4.5: 104

         title   category  rating
4    MYTRIDENT  bath-robe     4.7
7      My Room  bedsheets     4.7
22  London Rag      boots     5.0
32       VStar        bra     4.6
38   KARATCART   bracelet     4.6

In [72]:
#filtering specific category(watches)
watches=df[df["category"]=="watches"]
print("Total watch products:",len(watches))
watches[["title","category","rating","final_price"]].head()

Total watch products: 15

                 title category  rating   final_price
984             Fossil  watches     3.9   "₹4,997.00"
985               MVMT  watches     4.5  "₹10,416.00"
986              Timex  watches     4.9   "₹1,596.00"
987      Fantasy World  watches     3.7     "₹499.00"
988  French Connection  watches     4.4   "₹6,250.00"

In [73]:
#filtering using two conditions
#high rated and big discount
best_value=df[(df["rating"]>4.0) & (df["discount"]>50)]
print("High rated+ big discount products:",len(best_value))
best_value[["title","category","rating","discount","final_price"]].head()

High rated+ big discount products: 238

      title   category  rating  discount  final_price
2     Lavie  backpacks     4.4      65.0  "₹2,999.00"
3    F Gear  backpacks     4.4      52.0  "₹1,675.00"
7   My Room  bedsheets     4.7      54.0  "₹2,999.00"
8   My Room  bedsheets     4.5      54.0  "₹2,999.00"
17   Arrabi  bedsheets     4.3      76.0  "₹6,329.00"

In [74]:
#sorting

In [75]:
#sorting by rating
top_rated=df.sort_values("rating",ascending=False)
top_rated[["title","category","rating","final_price"]].head(10)

              title        category  rating  final_price
996           GUESS         watches     5.0  "₹8,900.00"
22       London Rag           boots     5.0  "₹3,839.00"
52      Bruchi CLUB          briefs     5.0    "₹310.00"
48            Zoiro          briefs     5.0    "₹499.00"
658           ASICS          shorts     5.0  "₹1,149.00"
437        VASTRADO          kurtas     5.0    "₹539.00"
917  Bannos Swagger     track-pants     5.0  "₹1,699.00"
88       ellementry         cutlery     5.0  "₹1,750.00"
881           MANGO            tops     5.0  "₹2,490.00"
239      Rustorange  ethnic-dresses     5.0  "₹1,484.00"

In [76]:
#sorting by discount
most_discounted=df.sort_values("discount",ascending=False)
most_discounted[["title","category","rating","discount","final_price"]].head(10)

            title       category  rating  discount   final_price
990     TIMESMITH        watches     3.7      88.0   "₹2,499.00"
21        Mactree          boots     3.9      88.0   "₹1,087.00"
228    Kord Store       earrings     4.4      88.0     "₹542.00"
236        ZENEME       earrings     0.0      87.0     "₹389.00"
447         Ishin         kurtas     0.0      86.0     "₹545.00"
357     High Star        jackets     3.9      85.0   "₹4,549.00"
920  Nasher Miles    trolley-bag     3.3      85.0  "₹17,995.00"
491  Swiss Design  outdoor-masks     3.0      85.0     "₹225.00"
767  Thomas Scott    sweatshirts     3.6      85.0   "₹4,799.00"
356     High Star        jackets     4.1      85.0   "₹3,749.00"

### 5.Remove duplicates.

In [77]:
print("Total no of duplicates",df.duplicated().sum())

Total no of duplicates 0

In [78]:
print("Duplicate product_ids",df["product_id"].duplicated().sum())

Duplicate product_ids 0

In [79]:
before=len(df)
df=df.drop_duplicates()
after=len(df)
print("Duplicates Removed:",(before-after))

Duplicates Removed: 0

### 6.Create a derived column (total_amount = price * quantity).

In [80]:
#creating quantity column

In [81]:
df['quantity']=1
print("quantity column created")
df[["title","final_price","quantity"]].head(10)

quantity column created

            title  final_price  quantity
0     Lino Perros  "₹3,995.00"         1
1  Tommy Hilfiger  "₹2,899.00"         1
2           Lavie  "₹2,999.00"         1
3          F Gear  "₹1,675.00"         1
4       MYTRIDENT  "₹2,899.00"         1
5             H&M  "₹1,399.00"         1
6      AVI Living  "₹1,399.00"         1
7         My Room  "₹2,999.00"         1
8         My Room  "₹2,999.00"         1
9      Story@home  "₹2,199.00"         1

In [82]:
df['final_price']=df['final_price'].astype(str)
df['final_price']=df['final_price'].str.replace('₹','',regex=False)
df['final_price']=df['final_price'].str.replace(',','',regex=False)
df['final_price']=df['final_price'].str.replace('"','',regex=False)
df['final_price']=df['final_price'].astype(float)

In [83]:
df["total_amount"]=df["final_price"]*df["quantity"]

In [84]:
df[["title","final_price","quantity","total_amount"]].head()

            title  final_price  quantity  total_amount
0     Lino Perros       3995.0         1        3995.0
1  Tommy Hilfiger       2899.0         1        2899.0
2           Lavie       2999.0         1        2999.0
3          F Gear       1675.0         1        1675.0
4       MYTRIDENT       2899.0         1        2899.0

In [85]:
df.shape

(1000, 23)

### 7.Save the cleaned dataset as a new CSV file.

In [86]:
print("final Dataset info") 
print(df.shape)
print(df.columns.tolist())

final Dataset info
(1000, 23)
['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'seller_name', 'sizes', 'seller_information', 'best_offer', 'more_offers', 'category', 'quantity', 'total_amount']

In [87]:
df.to_csv("cleaned_Combined_dataset.csv",index=False)

In [88]:
verify=pd.read_csv("cleaned_Combined_dataset.csv")
verify

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,product_specifications,amount_of_stars,seller_name,sizes,seller_information,best_offer,more_offers,category,quantity,total_amount
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",unknown,"[{""size"":""Onesize""}]",Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,3995.0
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",unknown,"[{""size"":""Onesize""}]",Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,2899.0
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",unknown,"[{""size"":""S""}]",Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,2999.0
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,"[{""specification_name"":""Compartment Closure"",""...","{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",unknown,"[{""size"":""Onesize""}]",Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks,1,1675.0
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"[{""specification_name"":""Body or Garment Size"",...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Not Available,{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe,1,2899.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890,50.0,11890.0,INR,http://assets.myntassets.com/assets/images/136...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",unknown,"[{""size"":""Onesize""}]",Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,1,11890.0
996,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900,45.0,8900.0,INR,http://assets.myntassets.com/assets/images/168...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",unknown,"[{""size"":""Onesize""}]",Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,1,8900.0
997,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950,50.0,7950.0,INR,http://assets.myntassets.com/assets/images/170...,...,"[{""specification_name"":""Dial Material"",""specif...","{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",unknown,"[{""size"":""Onesize""}]",Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches,1,7950.0
998,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295,20.0,2636.0,INR,http://assets.myntassets.com/assets/images/192...,...,"[{""specification_name"":""Add-Ons"",""specificatio...","{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",Tru███m R███il,"[{""size"":""Onesize""}]",Sho███o. ███-10█████████enu███████████████████...,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches,1,2636.0
999,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699,31.0,699.0,INR,http://assets.myntassets.com/assets/images/186...,...,"[{""specification_name"":""Mat Thickness"",""specif...","{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",unknown,"[{""size"":""Medium""}]",Not Available,{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats,1,699.0